require_relative 'activation/activation'
require_relative 'activation/sigmoid'
require_relative 'activation/softmax'
require_relative 'activation/relu'
require_relative 'activation/leaky_relu'
require_relative 'activation/elu'
require_relative 'activation/softplus'
